Repository stolostron/observatorium, pull requests merged in 2024-08, with the labels that each got.

#113 chore: Add schedule to update Konflux files
  renovate.json
Labels: lgtm, approved

#114 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/observatorium-acm-210-pull-request.yaml
  .tekton/observatorium-acm-210-push.yaml
Labels: ok-to-test

#115 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/observatorium-acm-211-pull-request.yaml
  .tekton/observatorium-acm-211-push.yaml
Labels: ok-to-test

#116 Sync missing changes from `main` to `release-2.12`
  renovate.json
Labels: lgtm
