Repository stolostron/observatorium, pull requests merged in 2025-07, with the labels that each got.

#259 Update renovate.json
  renovate.json
Labels: lgtm, approved

#261 Konflux: set target branch for 2.14 pipelines
  .tekton/observatorium-acm-214-pull-request.yaml
  .tekton/observatorium-acm-214-push.yaml
Labels: lgtm, approved

#280 Konflux: another dup variable on push pipeline
  .tekton/observatorium-acm-215-push.yaml
Labels: lgtm, approved

#281 Konflux changes for release-2.13
  .tekton/observatorium-acm-213-pull-request.yaml
  .tekton/observatorium-acm-213-push.yaml
Labels: lgtm, approved

#284 Triggering image rebuild for ACM 2.15
  README.md
Labels: approved

#283 Konflux changes for release-2.11
  .tekton/observatorium-acm-211-pull-request.yaml
  .tekton/observatorium-acm-211-push.yaml
  Containerfile.operator
Labels: lgtm
