Repository stolostron/observatorium, pull requests merged in 2025-04, with the labels that each got.

#197 Bump x/crypto to v0.36.0 & x/oauth2 to v0.28.0
  Containerfile.operator
  Dockerfile
  go.mod
  go.sum
Labels: approved

#202 Add new SAST tasks to Konflux pipelines
  .tekton/observatorium-acm-214-pull-request.yaml
  .tekton/observatorium-acm-214-push.yaml
Labels: lgtm, approved, ok-to-test

#204 Use UBI9 in dockerfile
  Dockerfile
Labels: lgtm

#215 Update renovate.json
  renovate.json
Labels: lgtm, approved
